// Generated by CoffeeScript 1.6.3
(function() {
  var TexRenderer;

  module.exports = TexRenderer = (function() {
    function TexRenderer(options) {
      this.options = options || {};
    }

    TexRenderer.prototype.em = function(text) {
      return "\\textit{" + text + "}";
    };

    TexRenderer.prototype.strong = function(text) {
      return "\\textbf{" + text + "}";
    };

    TexRenderer.prototype.codespan = function(text) {
      return "\\texttt{" + text + "}";
    };

    TexRenderer.prototype.br = function(text) {
      return "" + text + "\n";
    };

    TexRenderer.prototype.del = function(text) {
      return text;
    };

    TexRenderer.prototype.link = function(href, title, text) {
      return "\\url{" + href + "}";
    };

    TexRenderer.prototype.image = function(href, title, text) {
      return "";
    };

    TexRenderer.prototype.code = function(code, language) {
      var highlighted, lines, _base, _base1, _base2, _base3, _base4, _base5, _base6;
      if ((_base = this.options).packageName == null) {
        _base.packageName = "listing";
      }
      if ((_base1 = this.options).packageOptions == null) {
        _base1.packageOptions = "";
      }
      if ((_base2 = this.options).resetLineNumbers == null) {
        _base2.resetLineNumbers = true;
      }
      if ((_base3 = this.options).minted == null) {
        _base3.minted = {};
      }
      if ((_base4 = this.options.minted).linenos == null) {
        _base4.linenos = true;
      }
      if ((_base5 = this.options.minted).bgcolor == null) {
        _base5.bgcolor = "codebg";
      }
      if (this.options.resetLineNumbers === true) {
        this.options.minted.firstnumber = 1;
      } else {
        if ((_base6 = this.options.minted).firstnumber == null) {
          _base6.firstnumber = 1;
        }
      }
      if ("highlight" in this.options && typeof this.options.highlight === "function") {
        highlighted = this.options.highlight.call(this, code, language);
      } else {
        highlighted = this.defaultHighlighting(code, language);
      }
      if (highlighted == null) {
        highlighted = code;
      }
      if (this.options.resetLineNumbers === false) {
        lines = code.split(/\r\n|\r|\n/);
        this.options.minted.firstnumber += lines.length;
      }
      return "\\begin{" + this.options.packageName + "}" + this.options.packageOptions + "\n" + highlighted + "\n\\end{" + this.options.packageName + "}\n\n";
    };

    TexRenderer.prototype.defaultHighlighting = function(code, language) {
      var mintedOpts, mintedOptsStr, optName, optValue, _ref;
      mintedOpts = [];
      _ref = this.options.minted;
      for (optName in _ref) {
        optValue = _ref[optName];
        if (optValue === true) {
          mintedOpts.push(optName);
        } else {
          mintedOpts.push(optName + "=" + optValue);
        }
      }
      mintedOptsStr = "[" + mintedOpts.join(",") + "]";
      if (language == null) {
        language = this.options.defaultLanguage || "text";
      }
      return "\\begin{minted}" + mintedOptsStr + "{" + language + "}\n" + code + "\n\\end{minted}";
    };

    TexRenderer.prototype.paragraph = function(text) {
      return "" + text + "\n\n";
    };

    TexRenderer.prototype.html = function(html) {
      return html;
    };

    TexRenderer.prototype.heading = function(text, level) {
      var headingMap;
      if (level < 1 || level > 5) {
        return "" + text + "\n\n";
      }
      headingMap = ["\\section{" + text + "}", "\\subsection{" + text + "}", "\\subsubsection{" + text + "}", "\\paragraph{" + text + "}", "\\subparagraph{" + text + "}"];
      return headingMap[level - 1] + "\n\n";
    };

    TexRenderer.prototype.hr = function() {
      return "\\pagebreak\n\n";
    };

    TexRenderer.prototype.list = function(body, ordered) {
      if (ordered) {
        return "\\begin{enumerate}\n" + body + "\\end{enumerate}\n\n";
      } else {
        return "\\begin{itemize}\n" + body + "\\end{itemize}\n\n";
      }
    };

    TexRenderer.prototype.listitem = function(text) {
      return "\\item " + text + "\n";
    };

    TexRenderer.prototype.table = function(header, body) {
      return "" + header + body + "\n\n";
    };

    TexRenderer.prototype.tablerow = function(content) {
      return content;
    };

    TexRenderer.prototype.tablecell = function(content, flags) {
      return content;
    };

    return TexRenderer;

  })();

}).call(this);
